### ISSUE TITLE
Implement Non-Approximate Hotelling T2 Function

### ISSUE THREAD

**Issue by WarrenZhu050413** [cjerzak/fastrerandomize-software#10]
The current implementation of Hotelling T2 function approximates the covariance matrix with a diagonal matrix. An implementation of a non-approximate version would assist users who anticiate strong correlation between its covariates

**Comment by cjerzak** [comment]
This should work easily on Nvidia GPU. The reason we used the diagonalized version was failure of the full covariance version using the Metal backend (that is, failure on Apple GPU). I will re-test on updated version of jax-metal; if it's still broken, we can add conditional handling.
