### ISSUE TITLE
Update Tutorial With New Monte Carlo Functions and Complete VectorizedT2

### ISSUE THREAD

**Issue by WarrenZhu050413** [cjerzak/fastrerandomize-software#12]
Tutorial should be updated to reflect the new functionalities of the package

**Comment by WarrenZhu050413** [comment]
Ideally 3 tutorials:

1. Similar to the agriculture tutorial we have now

2. Going through a similar synthetic experiment with larger n, and go through the monte_carlo rerandomization scheme to demonstrate the need for both acceleration and the use of monte algorithms. Here since the matrices are larger, we could introduce the approximate matrix inversion too.

3. Go through a synthetic experiment with larger dimensions, and show that the need for lower acceptance thresholds and herefore higher number of rerandomization increases with the dimensions

**Comment by cjerzak** [comment]
In 3, could also explore various dim reduction strategies like pca

**Comment by WarrenZhu050413** [comment]
See #19
