### ISSUE TITLE
.onLoad instead of InitializeJax

### ISSUE THREAD

**Issue by WarrenZhu050413** [cjerzak/fastrerandomize-software#13]
https://stackoverflow.com/questions/20223601/r-how-to-run-some-code-on-load-of-package
https://github.com/tidyverse/dplyr/blob/bbcfe99e29fe737d456b0d7adc33d3c445a32d9d/R/zzz.r

Could use this instead of InitializeJax. @cjerzak, thoughts?

**Comment by cjerzak** [comment]
Happy to try this. We want as few fxn calls as possible so deleting initialize would be better than keeping it. Looking into now.

**Comment by WarrenZhu050413** [comment]
Don't use`onLoad` because Jax loading is slightly problematic. Instead, should build a BuildBackend Function. #22
