### ISSUE TITLE
GenerateCausalData Function

### ISSUE THREAD

**Issue by WarrenZhu050413** [cjerzak/fastrerandomize-software#15]
As of now, the `GenerateCausalData` function under `/fastrerandomize-software/fastrerandomize/R/FRR_GenerateData.R` is confusing and difficult to use. It may be better to dedicate a tutorial for generating different structures of data to test different hypotheses than implementing a function here. The function seems to obscure more than it helps. 

@cjerzak thoughts? Do you think a tutorial around using synthetic data to do power analysis is in the scope of this package? (I think a rudimentary sketch could potentially help orient the user)

**Comment by cjerzak** [comment]
I think in scope. I will go thru today and simplify and clarify the fxn. Deletion not necessarily a bad idea either. Or just putting the fxn in a tutorial in an improved version

**Comment by WarrenZhu050413** [comment]
Decision: Function Deleted. 

Migrate to Vignette/Tutorial #19
