### ISSUE TITLE
FRR_InitializeJAX.R—Improved Documentation of Helper Functions

### ISSUE THREAD

**Issue by WarrenZhu050413** [cjerzak/fastrerandomize-software#4]
Helper functions are defined in `FRR_InitializeJAX.R` without much documentation. This could be potentially confusing, and the helper functions may also be useful for users of the package.

**Comment by WarrenZhu050413** [comment]
Whenever calls a function that relies on Python libraries, do:

1. Check whether a python environment is loaded via reticulate.
2. If not, then search for a python environment `r-fast_rr`
3. If none exist, use miniconda to install it.
4. if no miniconda, prompt to download miniconda.

(Should have reference online. https://rstudio.github.io/reticulate/articles/package.html.)

**Comment by cjerzak** [comment]
FRR_InitializeJAX deleted
